name: Mountpoint-S3 Build

env:
  IMAGE_NAME: mountpoint-s3

on:
  push:
    branches: ["mountpoint-s3/alpine"]

  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set ENV
      - name: Set dynamic env
        run: |
          echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # Build Docker image and Export
      - name: Build & export docker image
        run: |
          docker build -f Dockerfile --tag ${{ env.IMAGE_NAME }}:amd64 --platform amd64 .
          mkdir -p images
          docker save ${{ env.IMAGE_NAME }} | gzip > images/${{ env.IMAGE_NAME }}.tar.gz

      # Upload to artifact
      - name: Upload Image to artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.IMAGE_NAME }} - Docker Image AMD64
          path: images/${{ env.IMAGE_NAME }}.tar.gz

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set ENV
      - name: Set dynamic env
        run: |
          echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # Build Docker image and Export
      - name: Build & export docker image
        run: |
          docker build -f Dockerfile --tag ${{ env.IMAGE_NAME }}:arm64 --platform arm64 .
          mkdir -p images
          docker save ${{ env.IMAGE_NAME }} | gzip > images/${{ env.IMAGE_NAME }}.tar.gz

      # Upload to artifact
      - name: Upload Image to artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.IMAGE_NAME }} - Docker Image ARM64
          path: images/${{ env.IMAGE_NAME }}.tar.gz
