name: Mountpoint-S3 Build

env:
  IMAGE_NAME: mountpoint-s3

on:
  push:
    branches: ["mountpoint-s3/alpine"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      # Build Docker image and Export
      - name: Build & export docker image
        run: |
          docker build -f Dockerfile --tag ${{ env.IMAGE_NAME }}:latest .
          mkdir -p images
          docker save ${{ env.IMAGE_NAME }} | gzip > images/${{ env.IMAGE_NAME }}.tar.gz

      # Upload to artifact
      - name: Upload APK Debug
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - Docker Image
          path: images/${{ env.IMAGE_NAME }}.tar.gz
